# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Import-Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - uses: mpi4py/setup-mpi@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade cython scipy numpy
        python -m pip install --upgrade setuptools
        python -m pip install flake8
        # https://github.com/pypa/pip/issues/12030#issuecomment-1546344047
        python -m pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip list
        python -m pip install '.[all]'
    - name: Test with pytest
      run: |
        python -m pytest tests/test_import.py  # other tests require the database, e.g., sms-wsj files

